
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: corso_security
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: napoli100
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/corso_security
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: napoli100

volumes:
  postgres_data: