spring.application.name=corso-security
spring.datasource.url=jdbc:postgresql://localhost:5432/corso_security
spring.datasource.username=postgres
spring.datasource.password=napoli100
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG